import { LureResult } from "./types";

/**
 * Mock fishing lure data. Each entry uses picsum.photos with a unique seed
 * and varied dimensions for a natural masonry layout.
 *
 * TODO: Replace with real product images once API integrations are live.
 */
export const MOCK_LURES: LureResult[] = [
  {
    id: "1",
    name: "Rapala X-Rap Shad",
    imageUrl: "https://picsum.photos/seed/lure1/400/500",
    productUrl: "https://www.rapala.com",
    aspectRatio: 0.8,
    tags: ["crankbait", "shad", "diving", "rapala"],
  },
  {
    id: "2",
    name: "Strike King KVD Jerkbait",
    imageUrl: "https://picsum.photos/seed/lure2/400/350",
    productUrl: "https://www.strikeking.com",
    aspectRatio: 1.14,
    tags: ["jerkbait", "suspending", "strike king"],
  },
  {
    id: "3",
    name: "Zoom Super Fluke",
    imageUrl: "https://picsum.photos/seed/lure3/400/300",
    productUrl: "https://www.zoombait.com",
    aspectRatio: 1.33,
    tags: ["soft plastic", "fluke", "bass", "zoom"],
  },
  {
    id: "4",
    name: "Heddon Zara Spook",
    imageUrl: "https://picsum.photos/seed/lure4/400/450",
    productUrl: "https://www.heddonlures.com",
    aspectRatio: 0.89,
    tags: ["topwater", "walk-the-dog", "heddon"],
  },
  {
    id: "5",
    name: "Booyah Buzzbait",
    imageUrl: "https://picsum.photos/seed/lure5/400/280",
    productUrl: "https://www.booyahbaits.com",
    aspectRatio: 1.43,
    tags: ["buzzbait", "topwater", "booyah"],
  },
  {
    id: "6",
    name: "Berkley PowerBait Ribbontail",
    imageUrl: "https://picsum.photos/seed/lure6/400/520",
    productUrl: "https://www.berkley-fishing.com",
    aspectRatio: 0.77,
    tags: ["soft plastic", "worm", "berkley", "ribbontail"],
  },
  {
    id: "7",
    name: "Megabass Vision 110",
    imageUrl: "https://picsum.photos/seed/lure7/400/360",
    productUrl: "https://www.megabassusa.com",
    aspectRatio: 1.11,
    tags: ["jerkbait", "suspending", "megabass", "premium"],
  },
  {
    id: "8",
    name: "Gary Yamamoto Senko 5\"",
    imageUrl: "https://picsum.photos/seed/lure8/400/480",
    productUrl: "https://www.yamamoto-baits.com",
    aspectRatio: 0.83,
    tags: ["soft plastic", "stick bait", "yamamoto", "senko"],
  },
  {
    id: "9",
    name: "Lucky Craft Pointer 100",
    imageUrl: "https://picsum.photos/seed/lure9/400/330",
    productUrl: "https://www.luckycraft.com",
    aspectRatio: 1.21,
    tags: ["jerkbait", "minnow", "lucky craft"],
  },
  {
    id: "10",
    name: "Rebel Pop-R",
    imageUrl: "https://picsum.photos/seed/lure10/400/400",
    productUrl: "https://www.lurenet.com",
    aspectRatio: 1.0,
    tags: ["topwater", "popper", "rebel"],
  },
  {
    id: "11",
    name: "Chatterbait Jack Hammer",
    imageUrl: "https://picsum.photos/seed/lure11/400/460",
    productUrl: "https://www.zmanfishing.com",
    aspectRatio: 0.87,
    tags: ["chatterbait", "bladed jig", "z-man"],
  },
  {
    id: "12",
    name: "Deps Slideswimmer 250",
    imageUrl: "https://picsum.photos/seed/lure12/400/300",
    productUrl: "https://www.deps.co.jp",
    aspectRatio: 1.33,
    tags: ["swimbait", "glide bait", "deps", "big bait"],
  },
  {
    id: "13",
    name: "Savage Gear 3D Bluegill",
    imageUrl: "https://picsum.photos/seed/lure13/400/380",
    productUrl: "https://www.savagegear.com",
    aspectRatio: 1.05,
    tags: ["swimbait", "bluegill", "savage gear"],
  },
  {
    id: "14",
    name: "Mepps Aglia Spinner",
    imageUrl: "https://picsum.photos/seed/lure14/400/550",
    productUrl: "https://www.mepps.com",
    aspectRatio: 0.73,
    tags: ["spinner", "inline spinner", "mepps", "trout"],
  },
  {
    id: "15",
    name: "Rooster Tail Original",
    imageUrl: "https://picsum.photos/seed/lure15/400/340",
    productUrl: "https://www.yakimabait.com",
    aspectRatio: 1.18,
    tags: ["spinner", "trout", "rooster tail"],
  },
  {
    id: "16",
    name: "Rapala Scatter Rap Crank",
    imageUrl: "https://picsum.photos/seed/lure16/400/420",
    productUrl: "https://www.rapala.com",
    aspectRatio: 0.95,
    tags: ["crankbait", "scatter rap", "rapala", "diving"],
  },
  {
    id: "17",
    name: "Strike King Red Eye Shad",
    imageUrl: "https://picsum.photos/seed/lure17/400/310",
    productUrl: "https://www.strikeking.com",
    aspectRatio: 1.29,
    tags: ["lipless crankbait", "rattle", "strike king"],
  },
  {
    id: "18",
    name: "Keitech Swing Impact FAT",
    imageUrl: "https://picsum.photos/seed/lure18/400/470",
    productUrl: "https://www.keitech.com",
    aspectRatio: 0.85,
    tags: ["soft plastic", "swimbait", "paddle tail", "keitech"],
  },
  {
    id: "19",
    name: "Spro Bronzeye Frog",
    imageUrl: "https://picsum.photos/seed/lure19/400/350",
    productUrl: "https://www.spro.com",
    aspectRatio: 1.14,
    tags: ["topwater", "frog", "hollow body", "spro"],
  },
  {
    id: "20",
    name: "Ima Flit 120",
    imageUrl: "https://picsum.photos/seed/lure20/400/290",
    productUrl: "https://www.ima-japan.com",
    aspectRatio: 1.38,
    tags: ["jerkbait", "suspending", "ima"],
  },
  {
    id: "21",
    name: "Zoom Trick Worm",
    imageUrl: "https://picsum.photos/seed/lure21/400/500",
    productUrl: "https://www.zoombait.com",
    aspectRatio: 0.8,
    tags: ["soft plastic", "worm", "finesse", "zoom"],
  },
  {
    id: "22",
    name: "Yo-Zuri Crystal Minnow",
    imageUrl: "https://picsum.photos/seed/lure22/400/360",
    productUrl: "https://www.yo-zuri.com",
    aspectRatio: 1.11,
    tags: ["minnow", "diving", "yo-zuri", "saltwater"],
  },
  {
    id: "23",
    name: "War Eagle Spinnerbait",
    imageUrl: "https://picsum.photos/seed/lure23/400/440",
    productUrl: "https://www.wareaglefishing.com",
    aspectRatio: 0.91,
    tags: ["spinnerbait", "bladed", "war eagle"],
  },
  {
    id: "24",
    name: "Jackall TN60 Lipless Crank",
    imageUrl: "https://picsum.photos/seed/lure24/400/320",
    productUrl: "https://www.jackall-lures.com",
    aspectRatio: 1.25,
    tags: ["lipless crankbait", "vibration", "jackall"],
  },
];
